import AuthSvc from './authservice'

const MicrosoftGraph = require('@microsoft/microsoft-graph-client');
const ACCESS_TOKEN_RESOURCE = 'https://graph.microsoft.com';

const NOTEBOOK_NAME = 'Okeears'
const SECTION_NAME = 'FY2018'
const PAGE_TITLE = 'Objectives';

const OBJECTIVES_LIST_ID = 'objectives';
const PAGE_TEMPLATE = 
`<html>
    <head>
        <title>${PAGE_TITLE}</title>
    </head>
    <body>
        <div>
        </div>
    </body>
</html>`;

export default class OkrService {
    constructor(config, tokenProvider) {
        
        // Stores mapping from user id to his objective's page id
        this.pageIds = new Map();

        this.graphClient = MicrosoftGraph.Client.init({
            // debugLogging: true,
            authProvider: (done) => {
                AuthSvc.withToken((token) => {
                    done(null, token);
                }, ACCESS_TOKEN_RESOURCE);
            }
        });
    }

    getObjectives(subjectId, dataHandler, errHandler) {
        this.getPageContent(subjectId, false, (document) => {
            
            // There are no objectives created yet
            if(!document) {
                return dataHandler([]);
            };

            let nodes = Array.from(document.querySelectorAll('li[data-id]'));
            let objectives = nodes.map((each) => {
                return {
                    id: each.getAttribute('data-id'),
                    // TODO: Probably this contains KRs text too - will see
                    statement: each.innerText
                };
            });
            
            dataHandler(objectives);
        }, errHandler);
    }

    createObjective(subjectId, objective, dataHandler, errHandler) {
        
        // Very simple unique id generator
        objective.id = Math.random().toString(36).substr(2, 9);
        
        // TODO: Escape HTML in objective's statement
        let statement = objective.statement;

        this.getPageContent(subjectId, true, (document) => {

            // If undefined - this is the first objective, 
            // need to add both ul and li tags
            let objectivesNode = document.querySelector(`ul[data-id="${OBJECTIVES_LIST_ID}"]`);

            let patchBody = objectivesNode ? 
                [{
                      'target': `#${OBJECTIVES_LIST_ID}`,
                      'action': 'append',
                      'content': `<li data-id="${objective.id}">${statement}</li>`
                }] : 
                [{
                    // In OneNote body means the first div on page
                    'target': `body`,
                    'action': 'append',
                    'content': `<ul data-id="${OBJECTIVES_LIST_ID}"><li data-id="${objective.id}">${statement}</li></ul>`
                }];

            this.graphClient
                .api(this.getSubjectPageContentUrl(subjectId))
                .patch(patchBody)
                .then((body) => dataHandler(objective))
                .catch(errHandler);
        }, errHandler);
    }

    changeObjective(subjectId, objective, dataHandler, errHandler) {
        let objectiveId = objective.id;
        // TODO: Escape HTML in objective's statement
        let statement = objective.statement;

        this.getPageContent(subjectId, false, (document) => {

            if(!document) {
                return errHandler({message: "Cannot found Objective's OneNote page."});
            };

            // Change operations should reference items by unique id generated by OneNote,
            // referencing by data-id is not supported
            let listNodeId = document.querySelector(`li[data-id="${objectiveId}"]`).getAttribute('id');

            let patchBody = [
                {
                'target': `${listNodeId}`,
                'action': 'replace',
                'content': `<li data-id="${objectiveId}">${statement}</li>`
                }];
            this.graphClient
                .api(this.getSubjectPageContentUrl(subjectId))
                .patch(patchBody)
                .then(dataHandler)
                .catch(errHandler); 
        }, errHandler);
    }

    deleteObjective(subjectId, objectiveId, successHandler, errHandler) {
        this.getPageContent(subjectId, false, (document) => {
            if(!document) {
                return errHandler({message: "Cannot found Objective's OneNote page."});
            };

            let listNodeId = document.querySelector(`li[data-id="${objectiveId}"]`).getAttribute('id');

            // OneNote does not support explicit delete operation, so patching with 
            // the empty item - it will be completely removed in OneNote page
            let patchBody = [
                {
                'target': `${listNodeId}`,
                'action': 'replace',
                'content':'<li></li>'
                }];
            this.graphClient
                .api(this.getSubjectPageContentUrl(subjectId))
                .patch(patchBody)
                .then(successHandler)
                .catch(errHandler); 
        }, errHandler);
    }

    createPage(subjectId, dataHandler, errHandler) {
        this.graphClient
            .api(`${this.getSubjectPrefix(subjectId)}/onenote/notebooks`)
            .post({ displayName: NOTEBOOK_NAME })
            .then((body) => {
                let notebookId = body.id;
                this.graphClient
                    .api(`${this.getSubjectPrefix(subjectId)}/onenote/notebooks/${notebookId}/sections`)
                    .post({ displayName: SECTION_NAME })
                    .then((body) => {
                        let sectionId = body.id;
                        this.graphClient
                            .api(`${this.getSubjectPrefix(subjectId)}/onenote/sections/${sectionId}/pages`)
                            .header("Content-Type", "application/xhtml+xml")
                            .post(PAGE_TEMPLATE)
                            .then((body) => {
                                let pageId = body.id;
                                this.setSubjectPageId(subjectId, pageId);
                                dataHandler(pageId);
                            })
                            .catch(errHandler);
                    })
                    .catch(errHandler);
            })
            // TODO: Handle error code 20117 "An item with this name already exists in this location."
            .catch(errHandler);
    }

    getPageContent(subjectId, createPage, dataHandler, errHandler) {
        let existingPageHandler = (dataHandler, errHandler) => {
            this.graphClient
                .api(this.getSubjectPageContentUrl(subjectId))
                .responseType('text')
                .query({"includeIDs":"true"})
                .get()
                .then((body) => {
                    let document = new DOMParser().parseFromString(body, "text/html");
                    dataHandler(document);
                })
                .catch(errHandler);
        };

        this.searchForOneNotePage(subjectId, (pageId) => {
            // Page id was got right now or taken from the cache
            if(pageId) {
                existingPageHandler(dataHandler, errHandler);
            } else {
                if(createPage) {
                    // TODO: We should not try to create pages for another users
                    this.createPage(subjectId, () => {
                        existingPageHandler(dataHandler, errHandler);
                    }, errHandler);
                } else {
                    // No objective's page found - that's fine
                    dataHandler(null);
                }
            }
        }, errHandler);
    }

    searchForOneNotePage(subjectId, dataHandler, errHandler) {
        let pageId = this.getSubjectPageId(subjectId);
        if(pageId) {
            dataHandler(pageId);
            return;
        }

        this.graphClient
            .api(`${this.getSubjectPrefix(subjectId)}/onenote/pages`)
            // Searches for the page with specified title across all user's notebooks
            .filter(`title eq '${PAGE_TITLE}'`)
            .select('id')
            .expand('parentNotebook')
            .get()
            .then((body) => {
                // Filter out pages from another notebooks, if any
                let pages = body.value.filter(page => page.parentNotebook.displayName == NOTEBOOK_NAME);
                if(pages.length == 1) {
                    let pageId = pages[0].id;
                    this.setSubjectPageId(subjectId, pageId);
                    dataHandler(pageId);
                } else if(pages.length == 0) {
                    dataHandler(null);
                } else {
                    errHandler({ message: `More than one '${PAGE_TITLE}' page found.`});
                }
            })
            .catch(errHandler);
    }

    getSubjectPrefix(subjectId) {
        // return subjectId ? `/users/${subjectId}` : '/me';
        return `/users/${subjectId}`;
    }

    setSubjectPageId(subjectId, pageId) {
        this.pageIds.set(subjectId, pageId);
    }

    getSubjectPageId(subjectId)
    {
        return this.pageIds.get(subjectId);
    }

    // Assuming that page is already created and its id is in cache
    getSubjectPageContentUrl(subjectId)
    {
        let prefix = this.getSubjectPrefix(subjectId);
        let pageId = this.getSubjectPageId(subjectId);
        return `${prefix}/onenote/pages/${pageId}/content`;
    }

    getObjectiveKeyResults(subjectId, objectiveId, dataHandler, errHandler) {
        // this.httpClient
        //     .get(`/subjects/${subjectId}/objectives/${objectiveId}/keyresults`)
        //     .then(resp => dataHandler(resp.data))
        //     .catch(err => errHandler(err));
    }

    putObjectiveKeyResults(subjectId, objectiveId, keyResultsObj, dataHandler, errHandler) {
        // this.httpClient
        //     .put(`/subjects/${subjectId}/objectives/${objectiveId}/keyresults`, keyResultsObj)
        //     .then(resp => dataHandler(resp.data))
        //     .catch(err => errHandler(err));
    }
}
